language: python
env:
  global:
  - CIBW_SKIP="cp27-* cp34-* *i686"
  - CIBW_BEFORE_BUILD_LINUX='curl -OsL https://bitbucket.org/eigen/eigen/get/3.3.7.tar.gz
    && tar xzf 3.3.7.tar.gz eigen-eigen-323c052e1731/Eigen --strip-components 1 &&
    cp -rf Eigen {project}/src && pip install numpy cython'
  - CIBW_BEFORE_BUILD_MACOS='brew cask uninstall --force oclint && brew install gcc
    eigen libomp && pip install numpy cython && exit 0'
  - CIBW_TEST_REQUIRES="numpy pytest pytest-cov"
  - CIBW_TEST_COMMAND="python -m pytest {project}/hafnian"
  - WHEELHOUSE_UPLOADER_USERNAME=AKIAJOU6ECM5Q7T6UUQQ
  - secure: lkBL0X+rNgWP54tf6W2xzdwl+XXeQCdPuCCKy1TPuJ1OJo4dIy6yMs4uapIz8s2atQ2x5SDC+tRQrQDnpLxy5rY0ikChdpkBCMoQvSJIoaaHTNK2hZjnTDtXTNjzkb6E70uWvRriVCy+B+LLjKjdtygIF0+2AE+SGNvW4fEZWP22TYv2s+tWY8GwMAYdaYb7UI3sI/0prIDTqdw/ZUiM22lJskR+BJxZGTR3gSzguE/umbK8tztLzKRUb9A5zXJWGCPY/eKgc20LzVeKCttv0fAGBGz6D/k3I2kUTj5+mBJ+vbNmfkOmgd0QyFGH6zBGLE0xl0vP9HYHhiCFFamTmbkjSLPym+MC5Up+YsMMRqWJDGA0/L3n6afbS3FUqKRb448t3eycvfPWACNpeLPXdaGLTx954O8tDQBMLAJa3dBEbJI31mN2sCVvXLj96SDBdSl/fyouClptGXKGraiqABzowAfmx6GRavCnZMoggmhYOLg5VknawDVSlnEFoGXss8tkZkjCjoj0xzW0aF100m6O7kAORWoa/YLAz2Dyvl+GgDMlsITCQuDs7JEWL0RABzpRw0li03FZd2a1FQkGPyYXROEW4n+tAwVjMAXsfeKafeAUMxzXlhjVc2g9+3rhLvIw3X0hgnr+dGxaLytMczUXwnouY1LbhOT2EWgW7+c=
matrix:
  include:
  - python: 3.5
    cache: pip
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
    env: WHEEL=0
  - sudo: required
    services:
    - docker
    env:
    - WHEEL=1
    - PIP=pip
    - PYTHON=python
  - os: osx
    xcode: 10.0.0
    language: generic
    env:
    - WHEEL=1
    - PIP=pip2
    - PYTHON=python2
before_install:
- |
  if [ "$WHEEL" = "0" ]; then
    sudo apt-get -qq update;
    sudo apt-get install -y gfortran libeigen3-dev;
  fi
install:
- |
  if [ "$WHEEL" = "0" ]; then
    pip install -r requirements.txt
    pip install pytest pytest-cov wheel codecov
    pip install -e .
  fi
script:
- if [ "$WHEEL" = "0" ]; then make coverage; fi
- |
  if [ "$WHEEL" = "1" ]; then
    $PIP install cibuildwheel==0.10.0
    $PIP install -r requirements.txt
    cibuildwheel --output-dir wheelhouse
    $PIP install https://github.com/joerick/libcloud/archive/v1.5.0-s3fix.zip
    $PIP install wheelhouse-uploader
    $PYTHON -m wheelhouse_uploader upload --provider-name S3 --local-folder wheelhouse/ xanadu-wheels
  fi
after_success:
- if [ "$WHEEL" = "0" ]; then codecov; fi
